consul:
  host: 192.168.89.4
  port: 8500
service:
  discoveryHost: 192.168.89.4
  healthCheck:
    timeout: 1s
    interval: 10s
    tcp: ${{ service.discoveryHost }}:${{ service.port }}
  maxRetry: 5
  retryInterval: 5000
  name: AuthService
  port: 50050
http:
  axios:
    timeout: 1000
database:
  host: 192.168.89.4
  port: 5432
  user: postgres
  password: postgres
  database: auth_ms
  synchronize: true
bcrypt:
  salt: 12
google:
  clientID: 354338577257-di8hl6sh8b0bk5skc0hsn6des4dvi08a.apps.googleusercontent.com
  clientSerect: Kd5OkqWIaxnA7Fxp-XmxqPnP
  callbackURL: /auth/google/callback
  passReqToCallback: true
  scope:
    - profile
    - email
  defaultPassword: abc123
  defaultPhoneNumber: 0901234567
  defaultCompanyName: unknown
  checkTokenUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=
facebook:
  appID: 181575936387690
  appSerect: 7dd046f2e3c49b4a34bb889933809530
  checkTokenUrl: https://graph.facebook.com/${id}/?access_token=${token}
logger:
  level: debug
  transports:
    - transport: console
      colorize: false
      datePattern: YYYY-MM-DD h:mm:ss
      label: auth-service
    - transport: file
      name: info
      json: false
      filename: auth-service.log
      datePattern: YYYY-MM-DD h:mm:ss
      label: auth-service
      # 200M
      maxsize: 209715200
      maxFiles: 10
    - transport: file
      name: error
      level: error
      json: false
      filename: auth-service.error.log
      datePattern: YYYY-MM-DD h:mm:ss
      label: auth-service
      # 200M
      maxsize: 209715200
      maxFiles: 10
confirmation:
  serect: 'bookoke2020'
  expiresIn : '24h'
jwt:
  private: "-----BEGIN RSA PRIVATE KEY-----
    MIIJKQIBAAKCAgEAwCQWeuCEEzwhhfjobHlzgSguBlN7St9E3amFov7TgEApNQzi
    7iNRVFB6IVhhLD0fMg+/19vAloJpxF3nRZDyfFX2Fa4Vhk6bCYT060/d9nyIt0FO
    qLpQNPf5F4vUSBEDcRNeUuI391Zl+Dw60j7xiYWUczUF3CDIIY2/6yo503QgQDxH
    DnfH4zDp5e/9CVI6X7ED1u8U7lJY4kEcaYUrhN8GuMA0T/gR7DZQK7LIHiWvk3mP
    cVTYi+VoxTQzLkpFHn5ZasDBAwWaHuREtUaL8n6GpBny9XR3wQL6hS6WGkO4HCId
    TEZqxGoWrGpVpp1lHIxgvPGoBCdT6XgThOBlleJ+/BdNiQVrh+b/FjQpBP4AHodu
    q2jfpQ9ij8AyF1tGNBVieDZRilLFz8WtJsbb6NoE5J06ISaklaRESVvOzh86uE+s
    KkAFomly9B2CwJ9up5YPkyV/ac01pk/lVWOVBNAXiviPQOe+MF+1EdzFXpk/Ve5z
    +pdrx0ZEQi2xei9iWm5hPc43keSJuDm08R6ixYMLVMP9FhUXoY+avx2+XNbgALEk
    6kYcS43MgPRhGUanI+mJ+34tprQQ1u45lpwwhL7sp/t34hpz/CsHu4H8qZF3ycIR
    yBS9BzRDwY0owik1u1uWLT3WaE4QmTagT7VhdO2KwNVD1zoKafebnFRGL0ECAwEA
    AQKCAgB+TrrgZ/sq0dqPwYK43FYLz6gBzJs+KuuQc8I/1hifNI5iK2h6d4kdThIb
    HYgzlrKNLEFG21UNHAn/ZmOEHbbp+XBd7CSGN+I/LcH7dnNJd7BAF5Rn4qKbT2/W
    BLu17ElA6iSVg9SaqZc6yg047NvHNaLS4UZK4NnvBMnnA8kjsjEJSRbE8gTa2urH
    ly3WFNH+2dTWVDCEQmnfwkG1NC/ZlutKRD+fWkod585oC4z2FHwJDF45eDcqL9Lh
    4GDMy1IIq7KINNIs9F/Ocuyf5hJVhMtp0Q0gQkH/BcA+ENPnzCCZjeuImrnRCJSD
    HxvS/aDcVYO6cXmr0VaeIatjLEhaTWv4ebzPry9Em+WraHIONlYMoRdQ0gAp6xwV
    4zn3+aVr32j1nazXnT8oR8tE+Q4ZBLnUBd1dq1AMdzOpwktW8gWD5Z8PvDGIZGVK
    MVfoAl8EMxDUv+Gngd0+fpT3w/af6m1Wv5zeR7y0Rdee04E+yUjRGK34G8zn7fvU
    oRIqZD+yWdpMXlcAWjVxxQ4Gw8n+98DcoD1i8bc08VSVW//8wzac4tAi/s3s/WXO
    hVK6UgJYSjVB+KrLbedSPgFMCiJeTJ2JpfieIJ6McBbhrTHE8FNAVxJp0GlWHqI5
    ioj+4X7Tl7FJOv2DhIfwxoBuBzWjFAB4yvBlNDhjJJ+1Zif9SQKCAQEA7HEvSbyj
    OLf8Db0tz14vUWVQRDJdi8v4pmfuqzugW792llTxBHD5WupiBRFsPZ0e2kqJGGl4
    eaMYNTwnFod7Oz25HUkICHvXsc3AFSZJpOqfDFdBaVsr+88inkVhcdR7cECL1UTg
    DAkKCCIHPci/Gq9nlqKVK0BE7TLPNIYtRXhBxC2SPjuZHmgyiomEPhgkBsDYbBmv
    u0vB9FdfkDDCgwvJo2JiidPgN8WMd2NWiUn1kzOjixmWabrwpbYuqd0at+Cjw3SN
    p1EuXcwvjza6pE6pI9Qm68Aq3AId+hvSykaJIU7zm6CsJkfwBxSuTWM5b3HcDTbL
    dFCQSYM322jh6wKCAQEA0AjMHY06lRO9OJd9qPbEXkwjQKIbD+yJ9jZRdgjg3avn
    w4yQuOdwjBj05Se+vcF05wDpA+jYowlb1E8jDiQIKnKXtp5JJHrrzcCFlD0tXZC/
    BWfjKLbZmbTCNNSxhHMigmdiUZUMUk6lwy/+X56Fc+R5SRlNsOEIIuCKoS9SDqLt
    9I7hhnsF2fSHQAFF0IFMEAOU5tIjAfhsgPRBWfebPEQd/j6puxzdT4WPIdG7P4py
    UvoJelRGJVvmdyyB9vhdqXiH1B+vbb+TU7s+uT6YDTAQW8Rtk8kEqBHElaNbt5re
    2ymv55kVtx+ulB1+0zQXI/44dl/5T/d8dBhC+Ja8gwKCAQAlLn9jNxjr2HL4riFA
    FO2X/TisIMd5LnBBquJrZwsGootBhMYKDsIHvAgCCAVfgw/RABujDSL27eDmrjjv
    YArO/BvaMRvkSaVXvqVQLh8yofq09BvDN6UpCh/Fh9+VCPcIZf4XYadh/SHouYEu
    BB2ZUrAVjierD4ZHTtAq0FbaL9kXwprW0oR3tacNBicXpLA1p6nhBgEOkRFFHWBX
    ynMsLHRfDx+z0O/XlWdLdwGqwUivB1XWkAWJRu6FAKtB5xVGiTr3h6KnByslcPCh
    steS8xPCIKCmPif/RQ31wN5bFNCHvmSsuo2Xz4Q9eNEYNlxX3C3gnhdMiUbHaK0m
    Ac5VAoIBAQCqUGl7UCJD5jMl37B64fwGD2NVCOIK+WZBclrivYYLNS+7QptBJglY
    SR5FdXKNO5KPhIlAMCMb5w+NE3TpoMompkZatd+/w/rFKfayVBuN3HDm5hRtQrWH
    Rxsv0Wm7u97mz+kITXQW9lhzIhmpAsjTBpvdIqAeTT0yAI6+Q1V0siMJ8ufkB1fV
    BoKr/d7AQvqYqbX/+s26UT3TnSTbmQE4J7Q+b+LZU1pEPl3eHCymapwKHrYftlrv
    PvvBWWjVXqSfmBPrsD0ZJpxhEozZb8tgEJdz6a6kLRBo4JMGxwTRnjMRTmG6w/Op
    RoDQtg0csCq5xulG0G/17fGvwiUiC5YtAoIBAQCyh29DXW9zUe7hhDbl/WHLZUzf
    LFRRWl3XVH9HTSb7LhrL0El9KWsQqOThP5WDm7q375rEsy9HSRmgkkfDZ+vr2j+x
    h3xcIp09iRgd1lZUd2RCLZEsVVKRxTseylZaCrOjbp8PF6jAXg5QVw6GET0Bgsv5
    /qLz+CotVxsATMwu0h57V6zjmiJeWjoRc03EKdGsavyf1wCd5KVzehPt88JRIz4M
    XP2Yv0/8LHuGFMw1Q3VcLh67Jsiy8wm/9PZKXG1W3+NYJhiSLhuEqq/Um/GGtMEv
    pO5YXNL8gZTpSg6hQm67obvS7ahoNXx7wZYuZk2lrfcbj53kyeOYzMcuzDTY
    -----END RSA PRIVATE KEY-----"
  public: "-----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwCQWeuCEEzwhhfjobHlz
    gSguBlN7St9E3amFov7TgEApNQzi7iNRVFB6IVhhLD0fMg+/19vAloJpxF3nRZDy
    fFX2Fa4Vhk6bCYT060/d9nyIt0FOqLpQNPf5F4vUSBEDcRNeUuI391Zl+Dw60j7x
    iYWUczUF3CDIIY2/6yo503QgQDxHDnfH4zDp5e/9CVI6X7ED1u8U7lJY4kEcaYUr
    hN8GuMA0T/gR7DZQK7LIHiWvk3mPcVTYi+VoxTQzLkpFHn5ZasDBAwWaHuREtUaL
    8n6GpBny9XR3wQL6hS6WGkO4HCIdTEZqxGoWrGpVpp1lHIxgvPGoBCdT6XgThOBl
    leJ+/BdNiQVrh+b/FjQpBP4AHoduq2jfpQ9ij8AyF1tGNBVieDZRilLFz8WtJsbb
    6NoE5J06ISaklaRESVvOzh86uE+sKkAFomly9B2CwJ9up5YPkyV/ac01pk/lVWOV
    BNAXiviPQOe+MF+1EdzFXpk/Ve5z+pdrx0ZEQi2xei9iWm5hPc43keSJuDm08R6i
    xYMLVMP9FhUXoY+avx2+XNbgALEk6kYcS43MgPRhGUanI+mJ+34tprQQ1u45lpww
    hL7sp/t34hpz/CsHu4H8qZF3ycIRyBS9BzRDwY0owik1u1uWLT3WaE4QmTagT7Vh
    dO2KwNVD1zoKafebnFRGL0ECAwEAAQ==
    -----END PUBLIC KEY-----"
  expireIn: "2 days"
redis:
  prefix: auth_ms
  auth_pass: cinnolab@@123
  host: ${{REDIS_HOST}}
  port: 6379
  ttl: 5
  cache_duration: 10
nodemailer:
  forgot_password_email_subject: Bookoke account password recovery
  logo: iVBORw0KGgoAAAANSUhEUgAAASwAAABQCAMAAACUNLhJAAAAM1BMVEUAAABEt09Et09Et09Et09Et09Et09Et09Et09Et09Et09Et09Et09Et09Et09Et09Et09d9bIWAAAAEHRSTlMAwEAQ8IDQMKBg4CBwsFCQPwx+VQAAB2FJREFUeNrsmutugzAMRp37BUj8/k+7iYla1CGBwjTW5vxDSlt6ZH9xWuA/I4PxQgiLVgjhTXLQ2UBJKYMxk0BCGAmdKi54jQvad18tXCZfcVTQqRMslZfpulpIQboCdBoETWE/QKeOmnpxvVZcHjoNXMQF23O+hbLdVrdF/JYt6DRQPeUP4PBBnyCajDRv9em0iaBZHjoNBnyQoNPA4EKEd8dZB7tQMW3siB+T8coijnvDKX94aXn8ZlI7u80OxdL6kNRKOBObrShxRqei8IUJ3hln8Ydx76ieq5Ppex8RlV+KQr0+TcVrI16ugd/EHfuUoNutSBmuS049OyE+lsML4DMiO7gWXgVHWzFUAmtBVpKP9kN3KsSwQKSb+1NZ1IpetSYpU17wHFojrT8pixDzW/+5LGpF6147/sWnyvN0eVYWoR0A3EDWoxV1OBxY9JG0q9pTuyNuEBXAHWSxVqwFFic/9SlF2DWyqLBvIYu1YiWwasU3rfz6S2QR6S6yeCvywGrLEqvL8WJZ8Tay6G9mr6qBxZFrWRP17SlZZsZrsuVuI4u2fOsqgdWWFekOTsnizwqYG8kCF1cH5oEHVlsW/Xhqz8pasJUokKOZkQq2GZKZCe4CWbwVM90kjeL7MivRobtBykL/vMynmqywIUsFgcQUyr5cjrRIe9eQ5czCuL8VB8hsxGnK8nS1Oj95/i+QpDCiJ+PKsmRRljIa1+ixoEqwCcTVZCkymw60YmbBum/OEvxVhs3hUvC9Th6qLBmRwc4gKmOBXJGVadWRViRa9ShoZe3LkivlsUTYkOXp/rl/gg8+w1c7Z7b0JgxDYbzvkPd/2m5pj5FsMaahM+303DUNP/aHJMuygn8N5c0MlsZ3llZFIWBJe8MAM5ix0vY1VhrCChaOQfhNieNCgRaHZfL6VjRkYU8mVx2AxrEh2wB4Y+kBrB3Xi6xAS2YFWhxWu1PHNGohE9Tg2s9jZ0MOwkTxYEDuq1y/lDn4oCQNKxFojWDtNxpdFvcsB27R5xuFnStKrMBDnB+eDpTV2YSsgZVAypM7cVjG3m040xYBS5YHDlZSNt1/gizmr5TyZKKS53CTiTvPuOLbSoCzlh8pVE81MFiNBqxFV8xmpd2hdE+9UZAsXql3Fln6OaQZrGYGTqgKebgw6o5oHaYSisKq9IJVVwwra6fvZ+LOPpdoAPN6uMS3GSyftrd4Cx014kiXYCh1SM+wisUY7kinbcULKyk59Kzod92s41KIWVhMCSu27pvN0wWK0zrOsNQTJVn5jDV3/6gUjSPwIC3AIjbSMKnpH9nL3KVw/QlWfaIQJJ/eF4yEm4CxYEXlAeuClvBHkOonjGMeY0sHK1jQfUzlnN/s4MOTFicEBSfDQlQMcwy4pTqEqTdkgoDlMbbnFGcl5WApK7ioV0wDy9LfVF3MLyiJFX5YnYL1MGGPAVhOqAg/ZVi4e+WsYGqSRiWavuG+Su6iGKyNS3NYZBYPqZEDDeTA3ADiOix+aXGYlgDLCrUDg6EB1uP9/LxIH4Z591t5HRbPCtIFLCIlwWr4/pNLId94tElBwRrqsbI8g0XaJyrC1wfd0D7ez8+rxccLuheyDsAaT1Djmx8M8En+0db+W5ioHVWSLTkeMvGRpHAFS0odUHiMwjIQYZswwCaGrZJuQ+LFtca62LoFbAWW38awsOWE9eg5higkpQYPpoNlsnjs18yHAhYCkwY8zazOYQs9V5nAyphJA9jpzisJ250DTxSwrn60pdvvsfJkCSFdbIrGM4dBipJTB93vhKcjMpvnRQdeDcUg6REUk0qfybBeiX2mT1lFo7voRVilnTbrFlazXqLRuDqQepaSjh00IbikyNY7UnLYFInx+3Qs8EIOS+vaXlADddLDEjwv/vHu/SoU/4yVzsFaNh/wwchDZ0YAA50yyZMLKXK9JGmS3VpXfjhXlMrKan+vaVksK2spky/Wmw+ywvgaNT6HOZKT4xIJUxGWwqTASyl/fWDhlcr8WBqwaJpYB4nSLVrBElZsfWcpe6G5Q6ta63R4Uq2SYVmzchTml4/CNi/tqOMdWnW28VS4ETUthZhwdToqsApPH7IWKyyJxi8f+xRFbBmy9NYvaIdBXExSYvX08f22s++s/+AQqpYMDApsLYnEg7xgNXq7gOULSS2vG0PCUmMI9wYe5Ffe66T7u+fRuQl8kzjeIYYRRHzAkn+QstvbLUdO6s/y4pLohXesSY1hbLtE697E8YLQA+TkbmWLzkAOQm5m0wvNbMx30zgPsJXhkm9r+fA94vvItDyav4jaybJVr8M5p2eGX1x+QS1Nxh3ttE3yUG9tUFLQrLPDHpIzlopxIXW+3tQ51hOXMkEVwXZd5cdbVC8acHV1SqmIBtxlcf/3tUxIKWLJo/kZ/VYgH9LPU+v+0l/4TspffYs5Vn0mUFv+/I//wu6c+3vfpttHJPvdZnGYd5L/11/fsIJL1v833/5UiFYk5dPfF2Ce1B7zJDWO/0kNVNKhTsSycqlsf0pfAHl+kFDXMe4YAAAAAElFTkSuQmCC
