version: '3'

services:
    auth_ms:
        build:
            context: .
        ports:
            - 50050:50050
        environment: 
            NODE_ENV: development
        networks:
            - microservices
        links:
            - "postgresql"
            - "redis"
    postgresql:
        image: bitnami/postgresql:11
        ports:
            - 5432:5432
        volumes:
            - postgresql_data:/bitnami/postgresql
            - ./database:/docker-entrypoint-initdb.d/create-data.sql
        environment:
            - POSTGRES_PASSWORD=postgres
        networks:
            - microservices
    redis:
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes"]        
        networks:
            - microservices
        volumes:
            - redis-data:/data
        ports:
            - 6379:6379
volumes:
    postgresql_data:
        driver: local
    redis-data:
        driver: local
networks:
    microservices: