version: "3"

services:
    auth_ms:
        build:
            context: .
        ports:
            - 50050:50050
        environment:
            NODE_ENV: local
            DISCOVERY_HOST: 192.168.89.4
            DATABASE_HOST: auth_ms_postgresql
            REDIS_HOST: auth_ms_redis
        networks:
            - auth_ms_network
        links:
            - auth_ms_postgresql
            - auth_ms_redis
    auth_ms_postgresql:
        image: bitnami/postgresql:11
        # ports:
        #     - 5432:5432
        volumes:
            - postgresql_data:/bitnami/postgresql
            - ./database:/docker-entrypoint-initdb.d/create-data.sql
        environment:
            - POSTGRES_PASSWORD=postgres
        networks:
            - auth_ms_network
    auth_ms_redis:
        image: "bitnami/redis:latest"
        command: redis-server --requirepass cinnolab@@123
        restart: always
        # ports:
        #     - 6379:6379
        volumes:
            - .:/usr/local/etc/redis
        networks:
            - auth_ms_network
volumes:
    postgresql_data:
        driver: local
networks:
    auth_ms_network:
