version: '3'
services:    
    postgresql:
        image: bitnami/postgresql:11
        ports:
            - 5432:5432
        volumes:
            - postgresql_data:/bitnami/postgresql
            - .:/docker-entrypoint-initdb.d/create-data.sql
        environment:
            - POSTGRES_PASSWORD=postgres        
volumes:
    postgresql_data:
        driver: local