version: '3'
services:  
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=cinnolab@@123    
    restart: always
    ports:
        - "6379:6379"
    volumes:
      - .:/usr/local/etc/redis